CREATE TABLE IF NOT EXISTS reports (
    id INTEGER NOT NULL PRIMARY KEY,
    created INTEGER NOT NULL,
    owner INTEGER NOT NULL,
    content TEXT NOT NULL,
    asset INTEGER NOT NULL,
    asset_type TEXT NOT NULL
)
