[package]
name = "tetratto-l10n"
version = "1.0.5"
edition = "2024"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
pathbufd = "0.1.4"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
