name = "com.tetratto.langs:en-US"
version = "1.0.0"

[data]
"general:link.home" = "Home"
"general:link.popular" = "Popular"
"general:link.following" = "Following"
"general:link.all" = "All"
"general:link.communities" = "Communities"
"general:link.next" = "Next"
"general:link.previous" = "Previous"
"general:link.source_code" = "Source code"
"general:link.reference" = "Reference"
"general:link.audit_log" = "Audit log"
"general:link.reports" = "Reports"
"general:link.ip_bans" = "IP bans"
"general:action.save" = "Save"
"general:action.delete" = "Delete"
"general:action.back" = "Back"
"general:action.report" = "Report"
"general:action.manage" = "Manage"
"general:action.open" = "Open"
"general:label.safety" = "Safety"
"general:label.share" = "Share"
"general:action.add_account" = "Add account"
"general:action.switch_account" = "Switch account"
"general:label.mod" = "Mod"
"general:label.file_report" = "File report"
"general:label.account_banned" = "Account banned"
"general:label.account_banned_body" = "Your account has been banned for violating our policies."

"dialog:action.okay" = "Ok"
"dialog:action.continue" = "Continue"
"dialog:action.cancel" = "Cancel"
"dialog:action.yes" = "Yes"
"dialog:action.no" = "No"
"dialog:action.save_and_close" = "Save and close"
"dialog:action.close" = "Close"

"auth:action.login" = "Login"
"auth:action.register" = "Register"
"auth:action.logout" = "Logout"
"auto:action.follow" = "Follow"
"auto:action.unfollow" = "Unfollow"
"auto:action.block" = "Block"
"auto:action.unblock" = "Unblock"
"auth:link.my_profile" = "My profile"
"auth:link.settings" = "Settings"
"auth:label.followers" = "Followers"
"auth:label.following" = "Following"
"auth:label.relationship" = "Relationship"
"auth:label.joined_communities" = "Joined communities"
"auth:label.recent_posts" = "Recent posts"
"auth:label.before_you_view" = "Before you view"

"communities:action.create" = "Create"
"communities:action.select" = "Select"
"communities:label.create_new" = "Create new community"
"communities:label.name" = "Name"
"communities:label.my_communities" = "My communities"
"communities:label.popular_communities" = "Popular communities"
"communities:action.join" = "Join"
"communities:action.cancel_request" = "Cancel request"
"communities:action.leave" = "Leave"
"communities:action.configure" = "Configure"
"communities:label.create_post" = "Create post"
"communities:label.content" = "Content"
"communities:label.posts" = "Posts"
"communities:label.questions" = "Questions"
"communities:label.not_allowed_to_read" = "You're not allowed to view this community's posts"
"communities:label.might_need_to_join" = "You might need to join this community in order to interact with it!"
"communities:label.create_reply" = "Create reply"
"communities:label.replies" = "Replies"
"communities:action.continue_thread" = "Continue thread"
"communities:tab.members" = "Members"
"communities:label.select_member" = "Select member"
"communities:label.user_id" = "User ID"
"communities:label.danger_zone" = "Danger zone"
"communities:label.delete_community" = "Delete community"
"communities:label.change_title" = "Change title"
"communities:label.new_title" = "New title"
"communities:label.pinned" = "Pinned"
"communities:label.edit_content" = "Edit content"
"communities:label.repost" = "Repost"
"communities:label.quote_post" = "Quote post"
"communities:label.expand_original" = "Expand original"
"communities:label.search" = "Search"
"communities:label.search_results" = "Search results"
"communities:label.query" = "Query"
"communities:label.join_new" = "Join new"
"communities:tab.posts" = "Posts"
"communities:tab.questions" = "Questions"

"notifs:action.mark_as_read" = "Mark as read"
"notifs:action.mark_as_unread" = "Mark as unread"
"notifs:action.clear" = "Clear"
"notifs:label.notifications" = "Notifications"

"settings:tab.general" = "General"
"settings:tab.account" = "Account"
"settings:tab.profile" = "Profile"
"settings:tab.theme" = "Theme"
"settings:tab.sessions" = "Sessions"
"settings:tab.images" = "Images"
"settings:label.change_password" = "Change password"
"settings:label.current_password" = "Current password"
"settings:label.delete_account" = "Delete account"
"settings:label.new_password" = "New password"
"settings:label.change_username" = "Change username"
"settings:label.new_username" = "New username"
"settings:label.two_factor_authentication" = "Two-factor authentication"
"settings:label.change_avatar" = "Change avatar"
"settings:label.change_banner" = "Change banner"
"settings:label.theme_hue" = "Theme hue"
"settings:label.theme_sat" = "Theme sat"
"settings:label.theme_lit" = "Theme lit"
"settings:label.import" = "Import"
"settings:label.export" = "Export"

"mod_panel:label.open_reported_content" = "Open reported content"
"mod_panel:label.manage_profile" = "Manage profile"
"mod_panel:label.permissions_level_builder" = "Permission level builder"
"mod_panel:label.warnings" = "Warnings"
"mod_panel:label.create_warning" = "Create warning"

"requests:label.requests" = "Requests"
"requests:label.community_join_request" = "Community join request"
"requests:label.review" = "Review"
"requests:label.ask_question" = "Ask question"
"requests:label.answer" = "Answer"
