name = "com.tetratto.langs:en-US"
version = "1.0.0"

[data]
"general:link.home" = "Home"
"general:link.popular" = "Popular"
"general:link.communities" = "Communities"
"general:action.save" = "Save"
"general:action.delete" = "Delete"
"general:action.back" = "Back"

"dialog:action.okay" = "Ok"
"dialog:action.continue" = "Continue"
"dialog:action.cancel" = "Cancel"
"dialog:action.yes" = "Yes"
"dialog:action.no" = "No"
"dialog:action.save_and_close" = "Save and close"


"auth:action.login" = "Login"
"auth:action.register" = "Register"
"auth:action.logout" = "Logout"
"auto:action.follow" = "Follow"
"auto:action.unfollow" = "Unfollow"
"auth:link.my_profile" = "My profile"
"auth:link.settings" = "Settings"
"auth:label.followers" = "Followers"
"auth:label.following" = "Following"
"auth:label.joined_communities" = "Joined communities"
"auth:label.recent_posts" = "Recent posts"

"communities:action.create" = "Create"
"communities:action.select" = "Select"
"communities:label.create_new" = "Create new community"
"communities:label.name" = "Name"
"communities:action.join" = "Join"
"communities:action.leave" = "Leave"
"communities:action.configure" = "Configure"
"communities:label.create_post" = "Create post"
"communities:label.content" = "Content"
"communities:label.posts" = "Posts"
"communities:label.create_reply" = "Create reply"
"communities:label.replies" = "Replies"
"communities:action.continue_thread" = "Continue thread"
"communities:tab.members" = "Members"
"communities:label.select_member" = "Select member"
"communities:label.user_id" = "User ID"

"notifs:action.mark_as_read" = "Mark as read"
"notifs:action.mark_as_unread" = "Mark as unread"
"notifs:action.clear" = "Clear"

"settings:tab.general" = "General"
"settings:tab.account" = "Account"
"settings:tab.profile" = "Profile"
"settings:tab.sessions" = "Sessions"
"settings:label.change_password" = "Change password"
"settings:label.current_password" = "Current password"
"settings:label.new_password" = "New password"
"settings:label.change_username" = "Change username"
"settings:label.new_username" = "New username"
"settings:label.change_avatar" = "Change avatar"
"settings:label.change_banner" = "Change banner"
